version: '3.8'
services:
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    name: nest-db
